version: 2.1

orbs:
  codecov: circleci/node@4.7

workflows:
  test-build:
    jobs:
      - test
      - build

jobs:
  test:
    docker:
      - image: node:17
    steps:
      - checkout
      - run: yarn
      - run: yarn test
  build:
    docker:
      - image: node:17
    steps:
      - checkout
      - run: yarn
      - run: yarn prod:build
